fullmetalupdate: Fix ostree-push failure
Issue: LINCD-8818

In follow two casees, ostree-push will fail.
case 1:
reproduce steps:
1. There is already some commits in branch container-hello-world
   in remote repo.
2. Create a new project, and use an config.cfg
   which will wrong ostree url address.
3. bitbake container-hello-world
   build will fail since push to wrong url
4. correct http address in config.cfg
5. bitbake container-hello-world will failed with error:
__main__.PushException: Remote commit 19e483429326943b2afc6a4dee513118cd01f46313029c5a87ebaf79ff050c21 not descendent of commit bc4917fcba087e9023289c1594f479c12f768872d24b21eb4f35ce1e52d57efa

fixed by replace ostree_remote_add_if_not_present with
ostree_remote_update, when url is updated, update the current url.

Case 2:
reproduce steps:
1. In project 1, push commit 1 to container-hello-world
2. In project 2, push commit 2/3 to container-hello-world
3. Go back to project 1, ostree-pull failed since maybe
   network issue, then commit 4 will be in project 1's local repo,
   then push will failed with error:
__main__.PushException: Shallow history from commit a16e58a32c1d176ed39912990d64fc6ad694b8af353adf2f71db5a6538333588 does not contain remote commit 739e5e2a2786c327a1d263f5032195c8128f3837724dbfd5036010b60e54aac8

Fixed by report error when pull is failed except the error is "Not Found".
"Not Found" means there is no remote branch, this will be the first
commit.

(LOCAL REV: NOT UPSTREAM) -- send to meta-lat later

Signed-off-by: Changqing Li <changqing.li@windriver.com>