genimage: update OSTREE_INITRD_PACKAGES
Issue: LIN1022-3438

From recipe initramfs-ostree.bb we can know that packages "grub
efibootmgr" only installed in initramfs-ostree-image when it is for
x86-64. So remove grub from default OSTREE_INITRD_PACKAGES, and only
install it for intel-x86-64 and amd-snowyowl-64, don't install for other
arm arch machines.

This can also fix error when running "geninitramfs
exampleyamls/initramfs-ostree-image-axxiaarm.yaml" for machine axxiaarm:
No match for argument: grub
Error: Unable to find a match: grub

grub is skipped for axxiaarm since following configs:
COMPATIBLE_HOST:armv7a = 'null'
COMPATIBLE_HOST:armv7ve = 'null'

(LOCAL REV: NOT UPSTREAM) -- sent to meta-lat on 20230224

Signed-off-by: Changqing Li <changqing.li@windriver.com>