ostree-settings.inc: Move do_write_wks_template:prepend to image_types_ostree.bbclass
Issue: LIN1022-1037

Refer to
https://docs.yoctoproject.org/bitbake/2.0/bitbake-user-manual/bitbake-user-manual-metadata.html#functions,

we can't define functions in conf files (The ostree-settings.inc is required by
conf/distro/ostree.conf, so move it to image_types_ostree.bbclass, this can
also fix errors when parsing the layer in layerindex:
Exception: NameError: name '__anon_131__foo_layers_meta_lat_conf_distro_include_ostree_settings_inc' is not defined

(LOCAL REV: NOT UPSTREAM) -- Will send to upstream later

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>