u-boot-uenv: reboot to enter rollback FIT image if the initial FIT image fails to validate
If initial FIT image (A) fails to validate or load correctly,
reboot to enter rollback FIT image (B). To avoid infinite reboot if
rollback FIT image (B) still fails, only reboot if initial FIT
image (A) fails. Here is the log:

==Booting default A==
41931872 bytes read in 1769 ms (22.6 MiB/s)
 ## Loading kernel from FIT Image at e0000000 ...
   Using 'wrhv' configuration
   Verifying Hash Integrity ... sha256,rsa2048:boot_key-  error!
Verification failed for '<NULL>' hash node in 'wrhv' config node
Failed to verify required signature 'key-boot_key'
Bad Data Hash
ERROR: can't get kernel image!
bootm 0xE0000000#wrhv failed
resetting �NOTICE:  Reset status: Destructive Reset (RUN)
NOTICE:  BL2: v2.5(release):bsp34.0-2.5-102-gc2f83865b
NOTICE:  BL2: Built : 07:11:12, Sep  6 2022
NOTICE:  BL2: Booting BL31

Issue: LINUXEXEC-20411

(LOCAL REV: NOT UPSTREAM) -- will send to upstream

Signed-off-by: Hongxu Jia <hongxu.jia@eng.windriver.com>